image: node:latest

stages:       
  - build

build-job:     
  stage: build
  script:
    - echo "Compiling the code..."
    - npm ci
    - echo "Compile successfully completed"
  artifacts:
    paths:
      - node_modules
